
var aptDetail = new function( 
    HOUSE_MANAGE_NO,
    PBLANC_NO,
    HOUSE_NM,
    HOUSE_SECD,
    HOUSE_SECD_NM,
    HOUSE_DTL_SECD,
    HOUSE_DTL_SECD_NM,
    RENT_SECD,
    RENT_SECD_NM,
    SUBSCRPT_AREA_CODE,
    SUBSCRPT_AREA_CODE_NM,
    HSSPLY_ZIP,
    HSSPLY_ADRES,
    TOT_SUPLY_HSHLDCO,
    RCRIT_PBLANC_DE,
    RCEPT_BGNDE,
    RCEPT_ENDDE,
    SPSPLY_RCEPT_BGNDE,
    SPSPLY_RCEPT_ENDDE,
    GNRL_RNK1_CRSPAREA_RCEPT_PD,
    GNRL_RNK1_ETC_GG_RCPTDE_PD,
    GNRL_RNK1_ETC_AREA_RCPTDE_PD,
    GNRL_RNK2_CRSPAREA_RCEPT_PD,
    GNRL_RNK2_ETC_GG_RCPTDE_PD,
    GNRL_RNK2_ETC_AREA_RCPTDE_PD,
    PRZWNER_PRESNATN_DE,
    CNTRCT_CNCLS_BGNDE,
    CNTRCT_CNCLS_ENDDE,
    HMPG_ADRES,
    CNSTRCT_ENTRPS_NM,
    MDHS_TELNO,
    BSNS_MBY_NM,
    MVN_PREARNGE_YM,
    SPECLT_RDN_EARTH_AT,
    MDAT_TRGET_AREA_SECD,
    PARCPRC_ULS_AT,
    IMPRMN_BSNS_AT,
    PUBLIC_HOUSE_EARTH_AT,
    LRSCL_BLDLND_AT,
    NPLN_PRVOPR_PUBLIC_HOUSE_AT,
    DETAIL_LIST
){
    this.HOUSE_MANAGE_NO = HOUSE_MANAGE_NO
    this.PBLANC_NO = PBLANC_NO
    this.HOUSE_NM = HOUSE_NM
    this.HOUSE_SECD = HOUSE_SECD
    this.HOUSE_SECD_NM = HOUSE_SECD_NM
    this.HOUSE_DTL_SECD = HOUSE_DTL_SECD
    this.HOUSE_DTL_SECD_NM = HOUSE_DTL_SECD_NM
    this.RENT_SECD = RENT_SECD
    this.RENT_SECD_NM = RENT_SECD_NM
    this.SUBSCRPT_AREA_CODE = SUBSCRPT_AREA_CODE
    this.SUBSCRPT_AREA_CODE_NM = SUBSCRPT_AREA_CODE_NM
    this.HSSPLY_ZIP = HSSPLY_ZIP
    this.HSSPLY_ADRES = HSSPLY_ADRES
    this.TOT_SUPLY_HSHLDCO = TOT_SUPLY_HSHLDCO
    this.RCRIT_PBLANC_DE = RCRIT_PBLANC_DE
    this.RCEPT_BGNDE = RCEPT_BGNDE
    this.RCEPT_ENDDE = RCEPT_ENDDE
    this.SPSPLY_RCEPT_BGNDE = SPSPLY_RCEPT_BGNDE
    this.SPSPLY_RCEPT_ENDDE = SPSPLY_RCEPT_ENDDE
    this.GNRL_RNK1_CRSPAREA_RCEPT_PD = GNRL_RNK1_CRSPAREA_RCEPT_PD
    this.GNRL_RNK1_ETC_GG_RCPTDE_PD = GNRL_RNK1_ETC_GG_RCPTDE_PD
    this.GNRL_RNK1_ETC_AREA_RCPTDE_PD = GNRL_RNK1_ETC_AREA_RCPTDE_PD
    this.GNRL_RNK2_CRSPAREA_RCEPT_PD = GNRL_RNK2_CRSPAREA_RCEPT_PD
    this.GNRL_RNK2_ETC_GG_RCPTDE_PD = GNRL_RNK2_ETC_GG_RCPTDE_PD
    this.GNRL_RNK2_ETC_AREA_RCPTDE_PD = GNRL_RNK2_ETC_AREA_RCPTDE_PD
    this.PRZWNER_PRESNATN_DE = PRZWNER_PRESNATN_DE
    this.CNTRCT_CNCLS_BGNDE = CNTRCT_CNCLS_BGNDE
    this.CNTRCT_CNCLS_ENDDE =CNTRCT_CNCLS_ENDDE
    this.HMPG_ADRES = HMPG_ADRES
    this.CNSTRCT_ENTRPS_NM = CNSTRCT_ENTRPS_NM
    this.MDHS_TELNO = MDHS_TELNO
    this.BSNS_MBY_NM = BSNS_MBY_NM
    this.MVN_PREARNGE_YM = MVN_PREARNGE_YM
    this.SPECLT_RDN_EARTH_AT = SPECLT_RDN_EARTH_AT
    this.MDAT_TRGET_AREA_SECD = MDAT_TRGET_AREA_SECD
    this.PARCPRC_ULS_AT = PARCPRC_ULS_AT
    this.IMPRMN_BSNS_AT = IMPRMN_BSNS_AT
    this.PUBLIC_HOUSE_EARTH_AT = PUBLIC_HOUSE_EARTH_AT
    this.LRSCL_BLDLND_AT = LRSCL_BLDLND_AT
    this.NPLN_PRVOPR_PUBLIC_HOUSE_AT = NPLN_PRVOPR_PUBLIC_HOUSE_AT
    this.DETAIL_LIST = DETAIL_LIST
    return {
        HOUSE_MANAGE_NO : HOUSE_MANAGE_NO,
        PBLANC_NO : PBLANC_NO,
        HOUSE_NM : HOUSE_NM,
        HOUSE_SECD : HOUSE_SECD,
        HOUSE_SECD_NM : HOUSE_SECD_NM,
        HOUSE_DTL_SECD : HOUSE_DTL_SECD,
        HOUSE_DTL_SECD_NM : HOUSE_DTL_SECD_NM,
        RENT_SECD : RENT_SECD,
        RENT_SECD_NM : RENT_SECD_NM,
        SUBSCRPT_AREA_CODE : SUBSCRPT_AREA_CODE,
        SUBSCRPT_AREA_CODE_NM : SUBSCRPT_AREA_CODE_NM,
        HSSPLY_ZIP : HSSPLY_ZIP,
        HSSPLY_ADRES : HSSPLY_ADRES,
        TOT_SUPLY_HSHLDCO : TOT_SUPLY_HSHLDCO,
        RCRIT_PBLANC_DE : RCRIT_PBLANC_DE,
        RCEPT_BGNDE : RCEPT_BGNDE,
        RCEPT_ENDDE : RCEPT_ENDDE,
        SPSPLY_RCEPT_BGNDE : SPSPLY_RCEPT_BGNDE,
        SPSPLY_RCEPT_ENDDE : SPSPLY_RCEPT_ENDDE,
        GNRL_RNK1_CRSPAREA_RCEPT_PD : GNRL_RNK1_CRSPAREA_RCEPT_PD,
        GNRL_RNK1_ETC_GG_RCPTDE_PD : GNRL_RNK1_ETC_GG_RCPTDE_PD,
        GNRL_RNK1_ETC_AREA_RCPTDE_PD : GNRL_RNK1_ETC_AREA_RCPTDE_PD,
        GNRL_RNK2_CRSPAREA_RCEPT_PD : GNRL_RNK2_CRSPAREA_RCEPT_PD,
        GNRL_RNK2_ETC_GG_RCPTDE_PD : GNRL_RNK2_ETC_GG_RCPTDE_PD,
        GNRL_RNK2_ETC_AREA_RCPTDE_PD : GNRL_RNK2_ETC_AREA_RCPTDE_PD,
        PRZWNER_PRESNATN_DE : PRZWNER_PRESNATN_DE,
        CNTRCT_CNCLS_BGNDE : CNTRCT_CNCLS_BGNDE,
        CNTRCT_CNCLS_ENDDE : CNTRCT_CNCLS_ENDDE,
        HMPG_ADRES : HMPG_ADRES,
        CNSTRCT_ENTRPS_NM : CNSTRCT_ENTRPS_NM,
        MDHS_TELNO : MDHS_TELNO,
        BSNS_MBY_NM : BSNS_MBY_NM,
        MVN_PREARNGE_YM : MVN_PREARNGE_YM,
        SPECLT_RDN_EARTH_AT : SPECLT_RDN_EARTH_AT,
        MDAT_TRGET_AREA_SECD : MDAT_TRGET_AREA_SECD,
        PARCPRC_ULS_AT : PARCPRC_ULS_AT,
        IMPRMN_BSNS_AT : IMPRMN_BSNS_AT,
        PUBLIC_HOUSE_EARTH_AT : PUBLIC_HOUSE_EARTH_AT,
        LRSCL_BLDLND_AT : LRSCL_BLDLND_AT,
        NPLN_PRVOPR_PUBLIC_HOUSE_AT : NPLN_PRVOPR_PUBLIC_HOUSE_AT,
        DETAIL_LIST : DETAIL_LIST
    }
}; 

var aptDetailType = new function(
    HOUSE_MANAGE_NO,
    PBLANC_NO,
    MODEL_NO,
    HOUSE_TY,
    SUPLY_AR,
    SUPLY_HSHLDCO,
    SPSPLY_HSHLDCO,
    MNYCH_HSHLDCO,
    NWWDS_HSHLDCO,
    LFE_FRST_HSHLDCO,
    OLD_PARNTS_SUPORT_HSHLDCO,
    INSTT_RECOMEND_HSHLDCO,
    ETC_HSHLDCO,
    TRANSR_INSTT_ENFSN_HSHLDCO,
    LTTOT_TOP_AMOUNT
){
    this.HOUSE_MANAGE_NO = HOUSE_MANAGE_NO
    this.PBLANC_NO = PBLANC_NO
    this.MODEL_NO = MODEL_NO
    this.HOUSE_TY = HOUSE_TY
    this.SUPLY_AR = SUPLY_AR
    this.SUPLY_HSHLDCO = SUPLY_HSHLDCO
    this.SPSPLY_HSHLDCO = SPSPLY_HSHLDCO
    this.MNYCH_HSHLDCO = MNYCH_HSHLDCO
    this.NWWDS_HSHLDCO = NWWDS_HSHLDCO
    this.LFE_FRST_HSHLDCO = LFE_FRST_HSHLDCO
    this.OLD_PARNTS_SUPORT_HSHLDCO = OLD_PARNTS_SUPORT_HSHLDCO
    this.INSTT_RECOMEND_HSHLDCO = INSTT_RECOMEND_HSHLDCO
    this.ETC_HSHLDCO = ETC_HSHLDCO
    this.TRANSR_INSTT_ENFSN_HSHLDCO = TRANSR_INSTT_ENFSN_HSHLDCO
    this.LTTOT_TOP_AMOUNT = LTTOT_TOP_AMOUNT
    return {
        HOUSE_MANAGE_NO : HOUSE_MANAGE_NO,
        PBLANC_NO : PBLANC_NO,
        MODEL_NO : MODEL_NO,
        HOUSE_TY : HOUSE_TY,
        SUPLY_AR : SUPLY_AR,
        SUPLY_HSHLDCO : SUPLY_HSHLDCO,
        SPSPLY_HSHLDCO : SPSPLY_HSHLDCO,
        MNYCH_HSHLDCO : MNYCH_HSHLDCO,
        NWWDS_HSHLDCO : NWWDS_HSHLDCO,
        LFE_FRST_HSHLDCO : LFE_FRST_HSHLDCO,
        OLD_PARNTS_SUPORT_HSHLDCO : OLD_PARNTS_SUPORT_HSHLDCO,
        INSTT_RECOMEND_HSHLDCO : INSTT_RECOMEND_HSHLDCO,
        ETC_HSHLDCO : ETC_HSHLDCO,
        TRANSR_INSTT_ENFSN_HSHLDCO : TRANSR_INSTT_ENFSN_HSHLDCO,
        LTTOT_TOP_AMOUNT : LTTOT_TOP_AMOUNT
    }
}

module.exports = {
    aptDetail : aptDetail,
    aptDetailType : aptDetailType
}